### ISSUE TITLE
Missing entities translations

### ISSUE THREAD

**Issue by gacek85** [b2bcodext/cms-form-builder#15]
When main application has CI with test for missing translations, main app build fails:
```
Found 11 missing translations:
b2bcode.cmsform.entity_grid_all_view_label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsForm]
b2bcode.cmsform.fields.label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsForm; Field: fields]
b2bcode.cmsform.cmsformfield.entity_grid_all_view_label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsFormField]
b2bcode.cmsform.cmsformfield.options.label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsFormField; Field: options]
b2bcode.cmsform.cmsfieldresponse.entity_grid_all_view_label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsFieldResponse]
b2bcode.cmsform.cmsformnotification.entity_grid_all_view_label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsFormNotification]
b2bcode.cmsform.cmsformnotification.id.label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsFormNotification; Field: id]
b2bcode.cmsform.cmsformnotification.email.label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsFormNotification; Field: email]
b2bcode.cmsform.cmsformnotification.form.label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsFormNotification; Field: form]
b2bcode.cmsform.cmsformnotification.template.label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsFormNotification; Field: template]
b2bcode.cmsform.cmsformresponse.entity_grid_all_view_label [Entity: B2bCode\Bundle\CmsFormBundle\Entity\CmsFormResponse]
```

Suggested translations:

```
b2bcode:
    cmsform:
        entity_grid_all_view_label: 'All forms'
        fields:
            label: 'Fields'
        cmsformfield:
            entity_grid_all_view_label: 'All fields'
            options:
                label: 'Options'
        cmsfieldresponse:
            entity_grid_all_view_label: 'All responses'
        cmsformnotification:
            entity_grid_all_view_label: 'All notifications'
            id:
                label: 'Id'
            email:
                label: 'Email'
            form:
                label: 'Form'
            template:
                label: 'Template'
        cmsformresponse:
            entity_grid_all_view_label: 'All responses'
```
